config/routes.rb
Currently::Application.routes.draw do

  root to: "static#home"

  devise_for :users

  match 'auth/:provider/callback', to: 'sessions#create', via: :get
  match 'auth/failure', to: redirect('/'), via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get
  match 'settings', to: 'settings#edit', as: 'settings', via: :get
  match 'settings', to: 'settings#update', as: 'update_settings', via: :put
  match 'sms-status-update', to: 'statuses#sms_create', via: :post
  match 'sms-ping', to: 'statuses#sms_ping', as: 'sms_ping', via: :get
  match 'about', to: 'static#about', as: 'about', via: :get

  resources :statuses, :nudges
  resources :connections, path: 'friends'
  match ':slug', to: 'users#show', constraints: lambda { |r| User.find_by_slug(r.params[:slug]).present? }, as: 'user', via: :get
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :activate_user_wall
  
  def edit
    @user = current_user
  end

  def update
    if @user = current_user.update_attributes(params[:user].permit(:slug, :phone))
      flash[:success] = "Settings updated"
    else
      flash[:error] = current_user.errors.empty? ? "Error" : current_user.errors.full_messages.to_sentence
    end
    redirect_to settings_path
  end
end

app/views/settings/edit.html.erb
<div class='container'>
  <%= form_for @user, class: 'form-inline', method: :put, url: update_settings_path do |f| %>
    <%= f.label 'Update username' %>
    <%= f.text_field :slug %>
    <%= f.label 'Update phone number' %>
    <%= f.text_field :phone, placeholder: '+19735557777' %>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  <% end %>

  <% unless @user.phone.blank? %>
    <div>
      <h2>
        Send a text message to 347-269-2048 to update your status!
        <%= link_to 'Send me a text from this number!', sms_ping_path, class: 'btn btn-primary' %>
      </h2>
    </div>
  <% end %>
</div>