config/routes.rb
Currently::Application.routes.draw do

  root to: "static#home"

  devise_for :users

  match 'auth/:provider/callback', to: 'sessions#create', via: :get
  match 'auth/failure', to: redirect('/'), via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get
  match 'settings', to: 'settings#edit', as: 'settings', via: :get
  match 'settings', to: 'settings#update', as: 'update_settings', via: :put
  match 'sms-status-update', to: 'statuses#sms_create', via: :post
  match 'sms-ping', to: 'statuses#sms_ping', as: 'sms_ping', via: :get
  match 'about', to: 'static#about', as: 'about', via: :get

  resources :statuses, :nudges
  resources :connections, path: 'friends'
  match ':slug', to: 'users#show', constraints: lambda { |r| User.find_by_slug(r.params[:slug]).present? }, as: 'user', via: :get
end

app/views/layouts/_footer.html.erb
<footer class="footer-3">
  <div class="container">
    <div class="row v-center">
        <div class="span2">                        
          <div class="span2">
              <a class="brand" href="<%= root_path %>">Currently</a>
          </div>
        </div>
        <div class="span7">                        
          <div class="span7">
          </div>
        </div>
        <div class="span3">                        
          <div class="span3">
            <h6>Made by <a href='http://www.andrewlin.net'> Andrew Lin </a></h6>
            <h6><a href="<%= about_path %>">About</a></h6>
            Theme by <a href='http://designmodo.github.io/startup-demo/'> Designmodo </a>
          </div>
        </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header class="header-10">
  <div class="container">
    <div class="navbar span12">
      <div class="navbar-inner">
        <button type="button" class="btn btn-navbar"> </button>
        <a class="brand" href="<%= root_path %>">Currently</a>
        <div class="nav-collapse collapse pull-right">
          <ul class="nav">
            <% if current_user %>
              <li><%= link_to current_user.name, user_path(current_user.slug) %></li>
              <li><%= link_to 'Settings', settings_path %></li>
              <li><a href="/signout">Sign Out</a></li>
            <% end %>
          </ul>
          <% unless current_user %>
            <form class="navbar-form pull-left">
              <%= render partial: 'shared/login_with_facebook' %>
            </form>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <script>
      var _rollbarParams = {'server.environment': '<%= Rails.env %>'};
      _rollbarParams['notifier.snippet_version'] = '2'; var _rollbar=['e607f76c16344dc6aee79da1f19202c5', _rollbarParams]; var _ratchet=_rollbar;
      (function(w,d){w.onerror=function(e,u,l,c,err){_rollbar.push({_t:'uncaught',e:e,u:u,l:l,c:c,err:err});};var i=function(){var s=d.createElement('script');var 
      f=d.getElementsByTagName('script')[0];s.src='//d37gvrvc0wt4s1.cloudfront.net/js/1/rollbar.min.js';s.async=!0;
      f.parentNode.insertBefore(s,f);};if(w.addEventListener){w.addEventListener('load',i,!1);}else{w.attachEvent('onload',i);}})(window,document);
    </script>
    <title><%= content_for?(:title) ? yield(:title) : 'Currently' %></title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', :media => 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body class='default-layout'>
    <%= render partial: 'layouts/navbar' %>
    <main>
      <div class='container-fluid'>
        <div class='row-fluid'>
          <div class='span12'>
            <div class='container'>
              <%= bootstrap_flash %>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <div id='wrap'></div>
    <div id='push'></div>
    <%= render partial: 'layouts/footer' %>
    <%= render partial: 'shared/google_analytics' %>
  </body>
</html>

app/views/layouts/static_layout.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <script>
      var _rollbarParams = {'server.environment': '<%= Rails.env %>'};
      _rollbarParams['notifier.snippet_version'] = '2'; var _rollbar=['e607f76c16344dc6aee79da1f19202c5', _rollbarParams]; var _ratchet=_rollbar;
      (function(w,d){w.onerror=function(e,u,l,c,err){_rollbar.push({_t:'uncaught',e:e,u:u,l:l,c:c,err:err});};var i=function(){var s=d.createElement('script');var 
      f=d.getElementsByTagName('script')[0];s.src='//d37gvrvc0wt4s1.cloudfront.net/js/1/rollbar.min.js';s.async=!0;
      f.parentNode.insertBefore(s,f);};if(w.addEventListener){w.addEventListener('load',i,!1);}else{w.attachEvent('onload',i);}})(window,document);
    </script>
    <title><%= content_for?(:title) ? yield(:title) : 'Currently' %></title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', :media => 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body class='static-layout'>
    <%= render partial: 'layouts/navbar' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
    <%= render partial: 'shared/google_analytics' %>
  </body>
</html>